PWS/Models/ViewModels/WhiskeyViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace PWS.Models.ViewModels
{
    public class WhiskeyViewModel
    {
        // -- Used for Whisky --
        public Whiskey? Whiskey { get; set; }

        // -- Used for Index / whisky list --
        public IEnumerable<Whiskey>? Whiskeys { get; set; }
        public List<int> YearSelect { get; set; } = new List<int>();

        // OrderBy
        [Display(Name = "OrderBy")]
        public SortMode SortMode { get; set; } = SortMode.TastedDate;
        [Display(Name = "Descending")]
        public bool OrderDes { get; set; } = true;

        // Filter
        [Display(Name = "Search Via Name")]
        public string? SearchString { get; set; } = "";
        [Display(Name = "Min Score")]
        [Range(0, 100)]
        public int ScoreMin { get; set; } = 0;
        [Display(Name = "Max Score")]
        [Range(0, 100)]
        public int ScoreMax { get; set; } = 100;
        [Display(Name = "Tasted Year")]
        public int SearchYear { get; set; } = -1;

        // Pagination
        private int currentPage = 0;
        public int CurrentPage {
            get
            {
                return currentPage;
            }
            set
            {
                if (value < 0)
                    value = 0;

                currentPage = value;
            }
        }
        [Display(Name = "Items per page")]
        public int AmountSelected { get; set; } = 0;
        private int totalItems = 0;
        public int TotalItems { 
            get
            {
                return totalItems;
            }
            set 
            { 
                if (value < 0)
                    value = 0;

                totalItems = value;
            }
        }
        public int TotalPages
        {
            get // Consider storing this rather than calcuating it every time it's called
            {
                if (AmountSelected == 0)
                    return 0;

                return (int)Math.Ceiling((double)TotalItems / (double)AmountSelected);
            }
        }
    }
}

PWS/Models/Whiskey.cs
using PWS.Services;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Globalization;

namespace PWS.Models
{
    public enum WhiskeyScoreSetting
    {
        NotScored = -1,
        ManualTotal = 0,
        ManualSub = 1,
        SurveyResults = 2
    }

    /// <summary>
    /// TODO. Make get finish, aroma, taste and tasting date from survey results!
    /// </summary>
    public class Whiskey
    {
        /// <summary>
        /// Determines how much characters MiniDescription Returns
        /// </summary>
        [NotMapped]
        public static readonly int MiniDescriptionLength = 100;
        private DateTime? tastedDate;
        private int whiskeyFinish = 0;
        private int whiskeyAroma = 0;
        private int whiskeyTaste = 0;

        [Key]
        public int WhiskeyId { get; set; }
        [Required]
        public required string WhiskeyName { get; set; }
        public string? WhiskeyDescription { get; set; }
        public ICollection<TastingItem> Tastings { get; set; } = [];
        /// <summary>
        /// Based on 'MiniDescriptionLength', returns a substring of 'Description'
        /// </summary>
        public string MiniDescription
        {
            get
            {
                if (WhiskeyDescription == null)
                    return "";

                int count = WhiskeyDescription.Length > MiniDescriptionLength ? MiniDescriptionLength : WhiskeyDescription.Length;

                return WhiskeyDescription.Substring(0, count);
            }
        }

        // --- Scores ---
        #region Scoring
        [Display(Name = "Score Setting", Description = "Determines how the score is set")]
        public WhiskeyScoreSetting WhiskeyScoreSetting { get; set; }
        public bool HasBeenTasted
        {
            get
            {
                if (WhiskeyScoreSetting == WhiskeyScoreSetting.NotScored)
                    return false;

                return true;
            }
        }

        ///// <summary>
        ///// Determines if the score is based on the surveyResults or is manually set
        ///// </summary>
        [Range(0, 100)]
        [Display(Name = "Finish")]
        public int WhiskeyFinish
        {
            get
            {
                if (WhiskeyScoreSetting == WhiskeyScoreSetting.SurveyResults)
                {
                    float? score = Tastings.OrderByDescending(x => x.Survey.End)
                                        .FirstOrDefault()?
                                        .GetAverageFinishScore();
                    return score != null ? (int)score : 0;
                }
                else return whiskeyFinish;
            }
            set => whiskeyFinish = value; 
        }
        [Range(0, 100)]
        [Display(Name = "Aroma")]
        public int WhiskeyAroma {
            get
            {
                if (WhiskeyScoreSetting == WhiskeyScoreSetting.SurveyResults)
                {
                    float? score = Tastings.OrderByDescending(x => x.Survey.End)
                                        .FirstOrDefault()?
                                        .GetAverageAromaScore();
                    return score != null ? (int)score : 0;
                }
                else return whiskeyAroma;
            }
            set => whiskeyAroma = value; 
        }
        [Range(0, 100)]
        [Display(Name = "Taste")]
        public int WhiskeyTaste { 
            get 
            {
                if (WhiskeyScoreSetting == WhiskeyScoreSetting.SurveyResults)
                {
                    float? score = Tastings.OrderByDescending(x => x.Survey.End)
                                        .FirstOrDefault()?
                                        .GetAverageTasteScore();
                    return score != null ? (int)score : 0;
                }
                else return whiskeyTaste;
            } 
            set => whiskeyTaste = value; 
        }         // TODO: Doesn't appear within database!
        private int totalScore { get; set; } = 0;
        /// <summary>
        /// GET: DoGenerateTotalScore is true, then return a generated value based on totalScore, else get a manually set value.
        /// SET: set manual totalScore.
        /// </summary>
        [Range(0, 100)]
        [Display(Name = "Total Score")]
        public int TotalScore
        {
            get
            {
                if (WhiskeyScoreSetting == WhiskeyScoreSetting.ManualSub)
                    return (WhiskeyFinish + WhiskeyAroma + WhiskeyTaste) / 3;

                if (WhiskeyScoreSetting == WhiskeyScoreSetting.NotScored)
                    return 0;
                if (WhiskeyScoreSetting == WhiskeyScoreSetting.SurveyResults)
                {
                    float? score = Tastings.OrderByDescending(x => x.Survey.End)
                                        .FirstOrDefault()?
                                        .GetAverageScore();
                    return score != null ? (int)score : 0;
                }
                    

                return totalScore;
            }
            set
            {
                totalScore = value;
            }
        }
        #endregion

        private string? whiskeyImageUrl = "";
        // This is here to ensure image url are from the server and not anywhere else to stop possible cross site attacks.
        [RegularExpression(@"^(?!(ht|f)tp(s?)\:\/\/)*([a-zA-Z0-9\-\.\?\,\'\/\\\+&%\$#_ ]*)?$", ErrorMessage = "Must not be a URL from another site. Must link to a file path locally on the server!")]
        public string? WhiskeyImageUrl { 
            get { return whiskeyImageUrl; }
            set
            {
                if (value == null)
                {
                    whiskeyImageUrl = value;
                    return;
                }

                whiskeyImageUrl = value.Replace("\\", "/");
            } 
        }
        /// <summary>
        /// Used for uploading files
        /// </summary>
        [NotMapped]
        public IFormFile? ImageFile { get; set; }

        // TODO: Make it get the tasted date from the results!
        public DateTime? TastedDate 
        { get { 
                if (WhiskeyScoreSetting == WhiskeyScoreSetting.SurveyResults && Tastings.Count > 0) 
                {
                    return Tastings?.OrderByDescending(x => x.Survey.End).FirstOrDefault()?.Survey.End; 
                } 
                else return tastedDate; }
            set => tastedDate = value; 
        }

        /// <summary>
        /// Get string detailing the tasting details. Month, year, rank, and theme of the tasting
		/// TODO: Get rank from survey results!
        /// </summary>
        /// <returns>{Month} {Year} | Rank {RankNo} | Theme: {Theme}</returns>
        public string GetTasteDetailsString()
        {
            if (WhiskeyScoreSetting == WhiskeyScoreSetting.NotScored)
                return "Not Ranked";

            if (TastedDate == null)
                return "Not Specified";
            if (WhiskeyScoreSetting == WhiskeyScoreSetting.SurveyResults && Tastings.Count() > 0)
            {
                var t = Tastings?.OrderByDescending(x => x.Survey.End).FirstOrDefault();
                var s = t.Survey;
                var tis = t.Survey.Tastings.OrderByDescending(x => x.GetAverageScore()).ToList();
                var pos = tis.FindIndex(x => x == t) + 1;

                return $"{TastedDate?.ToString("MMMM yyyy", CultureInfo.InvariantCulture)} | Rank:{pos.ToString()} | {s.Title}";
            }

                // {Month} {Year} | Rank {RankNo} | Theme: {Theme}
                return $"{TastedDate?.ToString("MMMM yyyy", CultureInfo.InvariantCulture)}";
        }

        public string GetTasteDateString()
        {
            if (WhiskeyScoreSetting == WhiskeyScoreSetting.NotScored)
                return "--";

            return TastedDate?.ToString("MMMM yyyy", CultureInfo.InvariantCulture);
        }

        public string GetScoreString()
        {
            if (WhiskeyScoreSetting == WhiskeyScoreSetting.NotScored)
                return "--";

            return TotalScore.ToString();
        }
        // This maybe should be else where but we might want access to this
        public static List<string> GetAllWhiskeyImageURLS()
        {
            var urls = new List<string>();
            urls.AddRange(Directory.GetFiles("wwwroot/images/tasted_whiskey/"));
            urls = urls.Select(x => x.Replace("wwwroot", "")).ToList();
            return urls;
        }

        /// <summary>
        /// Check if TastedDate is ok to be null or not.
        /// </summary>
        /// <returns></returns>
        public bool IsTastedDateVaild()
        {
            if (WhiskeyScoreSetting == WhiskeyScoreSetting.NotScored || WhiskeyScoreSetting == WhiskeyScoreSetting.SurveyResults)
                return true;

            if (TastedDate == null)
                return false;

            return true;
        }
    }
}

PWS/Controllers/WhiskeyDatabaseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PWS.Data;
using PWS.Models;
using PWS.Models.ViewModels;
using PWS.Services;

namespace PWS.Controllers
{
    /// <summary>
    /// TODO: Think of a better name rather than 'whisky database'
    /// TODO: Database connectivity & database seeding
    /// </summary>
    public class WhiskeyDatabaseController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly int _defaultAmountToShow = 10;

        public WhiskeyDatabaseController(ApplicationDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Returns a view with whiskys that match the filter.
        /// SearchYear does not function!
        /// </summary>
        /// <param name="pagination">What page the user is currently looking at.</param>
        /// <param name="searchName"></param>
        /// <param name="searchYear"></param>
        /// <returns></returns>
        public async Task<IActionResult> Index(WhiskeyViewModel? viewModel = null)
        {
            if (viewModel == null)
                viewModel = new();

            IQueryable<Whiskey> whiskeys;
            // Filter
            if (ModelState.IsValid)
            {
                whiskeys = _context.CompleteWhiskeyScore(viewModel.ScoreMin,viewModel.ScoreMax);
                if (!string.IsNullOrEmpty(viewModel.SearchString))
                {
                    whiskeys = whiskeys.Where(w => w.WhiskeyName.Contains(viewModel.SearchString));
                }

                if (viewModel.SearchYear > 1)
                    whiskeys = whiskeys.Where(w => w.TastedDate != null & w.TastedDate.Value.Year == viewModel.SearchYear);

                switch (viewModel.SortMode)
                {
                    case SortMode.Name:
                        whiskeys = whiskeys.OrderBy(w => w.WhiskeyName);
                        break;
                    case SortMode.ScoreSetting:
                        whiskeys = whiskeys.OrderBy(w => w.TotalScore);
                        break;
                    case SortMode.Score:
                        whiskeys = whiskeys.OrderBy(w => w.WhiskeyScoreSetting);
                        break;
                    case SortMode.TastedDate:
                        whiskeys = whiskeys.OrderBy(w => w.TastedDate);
                        break;
                    default:
                        whiskeys = whiskeys.OrderBy(w => w.WhiskeyName);
                        break;
                }
                if (viewModel.OrderDes)
                    whiskeys = whiskeys.Reverse();
            }
            else
            {
                whiskeys = _context.CompleteWhiskey();
            }


            var totalItems = whiskeys.Count();

            if (viewModel.AmountSelected <= 0)
                viewModel.AmountSelected = _defaultAmountToShow;

            whiskeys = whiskeys.Skip(viewModel.AmountSelected * viewModel.CurrentPage).Take(viewModel.AmountSelected);

            viewModel.Whiskeys = await whiskeys.ToListAsync();
            viewModel.YearSelect = await _context.GetAllWhiskeyYears().ToListAsync();

            viewModel.TotalItems = totalItems;
            //viewModel = new WhiskeyViewModel() { Whiskeys = selected, SearchString = searchName, SearchYear = searchYear, TotalItems = totalItems, CurrentPage = pagination, AmountSelected = _defaultAmountToShow };

            return View(viewModel);
        }

        [Route("/{controller}/{id:int}")]
        public IActionResult Whiskey(int id)
        {
            //var Whiskeys = _context.Whiskeys;
            //var selected = Whiskeys.Where(w => w.WhiskeyId == id).FirstOrDefault();

            var selected = _context.WhiskeyById(id);

            var viewModel = new WhiskeyViewModel() { Whiskey = selected };

            // TODO: Make a custom not found page for whisky!
            if (viewModel.Whiskey == null)
                return NotFound();

            return View(viewModel);
        }
    }
}

PWS/Views/WhiskeyDatabase/Index.cshtml
@{
    ViewData["Title"] = "Whiskys We've Tasted";
}

@model WhiskeyViewModel
@*
 // TODO: If no image exists, have a placeholder ready (just an icon)
 // TODO: Have it show how many results there are some where!
*@
<br />
<h2>Whiskys We've Tasted</h2>
<br />
<form class="" asp-controller="WhiskeyDatabase" asp-action="Index" id="filterForm" role="search" method="get">
    <div class="card card-body d-flex flex-row flex-wrap" style="gap:25px;">
        <div>
            <label asp-for="SearchString" class="form-label"></label>
            <input asp-for="SearchString" class="form-control">
        </div>
        <div>
            <label asp-for="SortMode" class="form-label"></label>
            <select class="form-select" asp-for="SortMode" asp-items="Html.GetEnumSelectList<SortMode>()">
            </select>
            <div class="">
                <input asp-for="OrderDes" class="" type="checkbox" />
                <label asp-for="OrderDes" class="control-label"></label>
            </div>
        </div>
        <div>
            <label class="form-label">Score Range</label>
            <div class="d-flex gap-3" style="width:fit-content">
                <span class="">
                    <input asp-for="ScoreMin" type="number" class="form-control d-block" style="width:75px;">
                </span>
                <span class="">
                    <input asp-for="ScoreMax" type="number" class="form-control d-block" style="width:75px;">
                </span>
            </div>
        </div>
        <div>
            <label asp-for="SearchYear" class="form-label"></label>

            <select class="form-select" asp-for="SearchYear">
                <option value="-1">All</option>
                @foreach (var year in Model.YearSelect)
                {
                    <option value="@year">@year</option>
                }
            </select>
        </div>

        <div>
            <label asp-for="AmountSelected" class="form-label"></label>

            <select class="form-select" asp-for="AmountSelected">
                <option value="10">10</option>
                <option value="20">20</option>
                <option value="40">40</option>
                <option value="60">60</option>
            </select>
        </div>


        <div class="ms-auto align-self-center d-flex">
            <a asp-controller="whiskeydatabase" asp-action="index" class="m-1 btn btn-lg btn-outline-primary">Clear filter</a>
            <button type="submit" class="m-1 btn btn-lg btn-primary">Apply Filter</button>
        </div>
    </div>
    <div asp-validation-summary="All" class="text-danger"></div>
</form>
<div class="d-flex flex-row flex-wrap gap-3 itemView" style="">
    @*TODO: Make these clickable!*@
    @foreach (var whisky in Model.Whiskeys)
    {
        <a class="text-decoration-none" asp-controller="WhiskeyDatabase" asp-action="Whiskey" asp-route-id="@whisky.WhiskeyId">
            <div class="card whiskeyCard">
                @*WhiskyImage*@
                <div class="card-img-top" alt="" style="position:relative; background:url('@whisky.WhiskeyImageUrl') center no-repeat; background-size: auto 100%;"></div>
                <hr style="margin: 0; padding: 0" />
                <div class="card-body">
                    @*WhiskyName*@
                    <div class="card-title fw-bold" style="height:3em;">@whisky.WhiskeyName</div>
                    @* <b class="card-title" style="height:18em; overflow:hidden">@whisky.WhiskeyName</b> *@
                    @*WhiskyScore*@
                    <p class="my-2">
                        @if (whisky.HasBeenTasted)
                        {
                            <i>Score:</i> <b>@whisky.GetScoreString()</b>
                            <br />
                            <i>Tasted On:</i> <b>@whisky.GetTasteDateString()</b>
                        }
                        else
                        {
                            <i>Not Tasted Yet</i>
                        }
                    </p>
                    @*Mini Whisky Description*@
                    @* <p class="card-text">@whisky.MiniDescription</p> *@
                </div>
            </div>
        </a>
    }

    @* <img class="card-img-top" src="~/images/Whiskey/Untitled1.jpg" alt="" style="height: 300px"> *@
</div>
@if (Model.Whiskeys.Count() == 0)
{
    <h4><i>No Items Found</i></h4>
}

@*TODO: Fix the fucking styling on this thing, the colors suck for it!*@
@*Should maybe make this a component*@
<nav aria-label="Whisky Results Pages" class="d-flex flex-column justify-content-centre mt-4">
    <ul class="pagination" style="margin-left: auto;margin-right: auto;">
        @if (Model.TotalPages > 1)
        {
            // Determines how many buttons appear. Breaks when not set to 5. Will need to be fixed if we want to show more or less than 5 buttons
            int maxButtons = 5;
            // How many buttons appear
            int pagesToShow = Model.TotalPages < maxButtons ? Model.TotalPages : maxButtons;
            // Shift determines the pages that appear within the pagination based on the current page, keeping the current page in the middle unless its the first one
            // (i.e: current page == 3 then [1] [2] [3] [4] [5] )
            // (i.e: current page == 4 then [2] [3] [4] [5] [6] )
            int shift = Model.CurrentPage >= maxButtons / 2 ? Model.CurrentPage - maxButtons / 2 : 0;
            // Cap the shift based on the total pages and amount of buttons that can show. Only apply if total pages > maxButtons
            if (Model.TotalPages > maxButtons && Model.CurrentPage > Model.TotalPages - (maxButtons / 2 + 1))
            {
                shift = Model.TotalPages - maxButtons;
            }
        @*
        @Model.TotalPages
        <br />
        @pagesToShow
        <br />
        @shift
        <br />
        @Html.Raw(Model.TotalPages - (maxButtons / 2 + 1))
        *@


        @*Previous button*@
        <li class="page-item @Html.Raw(Model.CurrentPage < 1 ? "disabled" : "")">
            <a class="page-link fw-bold" asp-controller="WhiskeyDatabase" asp-action="Index"    
            asp-route-CurrentPage="@Html.Raw(Model.CurrentPage-1)"
            asp-route-SearchString="@Model.SearchString"
            asp-route-SearchYear="@Model.SearchYear"
            asp-route-ScoreMin="@Model.ScoreMin"
            asp-route-ScoreMax="@Model.ScoreMax"
            asp-route-SortMode="@Model.SortMode"
            asp-route-OrderDes="@Model.OrderDes">
                🠄
            </a>
        </li>


        @*[1] [2] [3]*@
        @for (int i = 0; i < pagesToShow; i++)
        {
            int x = i + shift;
            if (x > Model.TotalPages - 1) // Break the loop when we reach the max pages
                break;

            <li class="page-item @Html.Raw(x > Model.TotalPages - 1 ? "disabled" : "") @Html.Raw(x == Model.CurrentPage ? "active" : "")">
                <a class="page-link" asp-controller="WhiskeyDatabase" asp-action="Index"
                asp-route-CurrentPage="@x"
                asp-route-SearchString="@Model.SearchString"
                asp-route-SearchYear="@Model.SearchYear"
                asp-route-ScoreMin="@Model.ScoreMin"
                asp-route-ScoreMax="@Model.ScoreMax"
                asp-route-SortMode="@Model.SortMode"
                asp-route-OrderDes="@Model.OrderDes">
                    @Html.Raw(x+1)
                </a>
            </li>
        }

        @*Next button*@
        <li class="page-item @Html.Raw(Model.CurrentPage + 1 == Model.TotalPages ? "disabled" : "")">
            <a class="page-link fw-bold" asp-controller="WhiskeyDatabase" asp-action="Index"
            asp-route-CurrentPage="@Html.Raw(Model.CurrentPage+1)"
            asp-route-SearchString="@Model.SearchString"
            asp-route-SearchYear="@Model.SearchYear"
            asp-route-ScoreMin="@Model.ScoreMin"
            asp-route-ScoreMax="@Model.ScoreMax"
            asp-route-SortMode="@Model.SortMode"
            asp-route-OrderDes="@Model.OrderDes">
                🠆
            </a>
        </li>
        }
    </ul>
        
</nav>
<p class="font-italic text-center mt-1"><em>Showing @(Model.AmountSelected > Model.TotalItems ? Model.TotalItems : Model.AmountSelected) of @Model.TotalItems found items.</em></p>

PWS/Views/WhiskeyDatabase/Whiskey.cshtml
@{
    ViewData["Title"] = "Whisky"; // TODO: Make it reflect the whisky being viewed
}
@model WhiskeyViewModel

<a href="javascript:window.history.back();" class="btn btn-lg p-0 mt-4 text-muted"><i class="bi bi-arrow-left-circle"></i> Back</a>
<nav aria-label="breadcrumb" style="--bs-breadcrumb-divider: '>';">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-action="index">WhiskyDatabase</a></li>
        <li class="breadcrumb-item"><a asp-action="index" asp-route-searchYear="@Model.Whiskey.TastedDate?.Year">@Model.Whiskey.TastedDate?.Year</a></li>
        <li class="breadcrumb-item active" aria-current="page">@Model.Whiskey.WhiskeyName</li>
    </ol>
</nav>

<br />
<div class="row gap-3">
    <div class="col-4 border-secondary" style="height: 500px; border-right: solid 1px;">
        @*Image*@
        <div class="" alt="" style="position:relative; background:url('@Model.Whiskey.WhiskeyImageUrl') center no-repeat; background-size: auto 100%; width:100%; height:100%; "></div>
    </div>

    <div class="col-6">
        @*Text*@
        <h2>@Model.Whiskey.WhiskeyName</h2>
        <h4><i>Score:</i> <b>@Model.Whiskey.TotalScore</b></h4>

        @*Make the below clickable to view the results page*@
        <div class="border-secondary py-2" style="width:100%; border-bottom: solid 1px; border-top: solid 1px;">
            @if (Model.Whiskey.WhiskeyScoreSetting == WhiskeyScoreSetting.SurveyResults)
            {
                <span>Tasted On: <a asp-controller="TastingResults" asp-action="Index" asp-route-year="@Model.Whiskey.TastedDate.Value.Year">@Model.Whiskey.GetTasteDetailsString()</a></span>
            }
            else
            {
                @Model.Whiskey.GetTasteDetailsString()
            }
        </div>
        @*Description*@
        <p class="my-2">
            @Model.Whiskey.WhiskeyDescription
        </p>
    </div>
</div>