PWS/Controllers/BlogAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PWS.Data;
using PWS.Models;
using PWS.Services;

namespace PWS.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BlogAdminController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UploadManager _uploadManager;

        public BlogAdminController(ApplicationDbContext context)
        {
            _context = context;
            _uploadManager = new UploadManager(this);
        }

        // GET: Blogs
        public async Task<IActionResult> Index()
        {
            return View(
                await _context.Blogs
                .Select(x => new Blog { Id = x.Id, Title = x.Title, Summary = x.Summary, PublishedDate = x.PublishedDate, UpdatedDate = x.UpdatedDate,IsPublished = x.IsPublished })
                .OrderBy(b => b.PublishedDate)
                .ToListAsync()
                );
        }

        // GET: Blogs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // GET: Blogs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Content,Summary,IsPublished,PublishedDate,UpdatedDate,ImageFile")] Blog blog)
        {
            blog.PublishedDate = DateTime.Now;
            blog.UpdatedDate = DateTime.Now;

            if (blog.ImageFile != null && ModelState.IsValid)
                _uploadManager.CheckImageFileState(blog.ImageFile);


            if (ModelState.IsValid)
            {
                _context.Add(blog);
                await _context.SaveChangesAsync();
                if (blog.ImageFile != null)
                {
                    blog.ImageUrl = await _uploadManager.AsyncSingleFileUpload(blog.ImageFile, blog.Id.ToString()); // Fun fact, after adding the item to the DB, EF will hydrate the model with ID. Thats why we can use it here.

                    await _context.SaveChangesAsync(); // Not prefered to have another update, but I don't know an easier way to get the generated id of a newly created item without creating it first
                }

                return RedirectToAction(nameof(Index));
            }
            return View(blog);
        }

        // GET: Blogs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs.FindAsync(id);
            if (blog == null)
            {
                return NotFound();
            }
            return View(blog);
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Content,Summary,IsPublished,PublishedDate,ImageFile")] Blog blog)
        {
            if (id != blog.Id)
            {
                return NotFound();
            }

            blog.UpdatedDate = DateTime.Today;

            // Check if this is the first time the blog is being published, update publish date
            if (!_context.Blogs.AsNoTracking().Where(b => id == b.Id).FirstOrDefault()!.IsPublished && blog.IsPublished)
            {
                blog.PublishedDate = DateTime.Today;
            }

            if (blog.ImageFile != null && ModelState.IsValid)
                _uploadManager.CheckImageFileState(blog.ImageFile);

            if (ModelState.IsValid)
            {
                if (blog.ImageFile != null)
                    blog.ImageUrl = await _uploadManager.AsyncSingleFileUpload(blog.ImageFile, blog.Id.ToString());

                try
                {
                    _context.Update(blog);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogExists(blog.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(blog);
        }

        // GET: Blogs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // POST: Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blog = await _context.Blogs.FindAsync(id);
            if (blog != null)
            {
                _uploadManager.DeleteUploadedImage(blog.ImageUrl);
                _context.Blogs.Remove(blog);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlogExists(int id)
        {
            return _context.Blogs.Any(e => e.Id == id);
        }
    }
}

PWS/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PWS.Models;
using PWS.Data;

namespace PWS.Controllers
{
    public class BlogController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BlogController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Blogs
        public async Task<IActionResult> Index()
        {
            var blogs = _context.Blogs.Where(b => b.IsPublished)
                .Select(x => new Blog { Id = x.Id, Title = x.Title, Summary = x.Summary, PublishedDate = x.PublishedDate, UpdatedDate = x.UpdatedDate, ImageUrl = x.ImageUrl }) // <= This sped up loading by a bunch
                .OrderByDescending(x => x.PublishedDate); 

            return View(await blogs.ToListAsync());
        }

        //public IActionResult Index()
        //{
        //    return View();
        //}
        [Route("/Blog/{id:int}")]
        public IActionResult BlogEntry(int id)
        {
            var blog = _context.Blogs.Where(b => b.Id == id && b.IsPublished)
                .FirstOrDefault();

            if (blog == null)
                return NotFound();

            return View(blog);
        }
    }
}

PWS/Controllers/GalleryController.cs
using Microsoft.AspNetCore.Mvc;
using PWS.Models;

namespace PWS.Controllers
{
    public class GalleryController : Controller
    {
        public IActionResult Index()
        {
            var galleryPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "GalleryPics");
            var imageFiles = Directory.EnumerateFiles(galleryPath)
                                      .Select(fileName => new GalleryImage
                                      {
                                          FileName = Path.GetFileName(fileName),
                                          FilePath = "/GalleryPics/" + Path.GetFileName(fileName)
                                      })
                                      .ToList();

            return View(imageFiles);
        }
    }
}

PWS/Controllers/WhiskeyAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PWS.Data;
using PWS.Models;
using PWS.Models.ViewModels;
using PWS.Services;

namespace PWS.Controllers
{
    [Authorize(Roles = "Admin")]
    public class WhiskeyAdminController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UploadManager _uploadManager;

        public WhiskeyAdminController(ApplicationDbContext context)
        {
            _context = context;
            _uploadManager = new UploadManager(this);
        }

        // GET: WhiskeyAdmin
        public async Task<IActionResult> Index(WhiskeyAdminViewModel? viewModel = null)
        {
            if (viewModel == null)
                viewModel = new();

            var whiskeys = _context.CompleteWhiskeyScore(viewModel.ScoreMin, viewModel.ScoreMax); ;

            if (!string.IsNullOrEmpty(viewModel.SearchString))
            {
                whiskeys = whiskeys.Where(w => w.WhiskeyName.Contains(viewModel.SearchString));
            }

            if (viewModel.SearchYear > 1)
                whiskeys = whiskeys.Where(w => w.TastedDate != null & w.TastedDate.Value.Year == viewModel.SearchYear);

            switch (viewModel.SortMode)
            {
                case SortMode.Name:
                    whiskeys = whiskeys.OrderBy(w => w.WhiskeyName);
                    break;
                case SortMode.ScoreSetting:
                    whiskeys = whiskeys.OrderBy(w => w.TotalScore);
                    break;
                case SortMode.Score:
                    whiskeys = whiskeys.OrderBy(w => w.WhiskeyScoreSetting);
                    break;
                case SortMode.TastedDate:
                    whiskeys = whiskeys.OrderBy(w => w.TastedDate);
                    break;
                default:
                    whiskeys = whiskeys.OrderBy(w => w.WhiskeyName);
                    break;
            }
            if (viewModel.OrderDes)
                whiskeys = whiskeys.Reverse();

            viewModel.Whiskeys = await whiskeys.ToListAsync();
            viewModel.YearSelect = await _context.GetAllWhiskeyYears().ToListAsync();

            //await _context.Whiskeys.ToListAsync()
            return View(viewModel);
        }

        // GET: WhiskeyAdmin/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var whiskey = _context.WhiskeyById(id);
                
            if (whiskey == null)
            {
                return NotFound();
            }

            return View(whiskey);
        }

        // GET: WhiskeyAdmin/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: WhiskeyAdmin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("WhiskeyId,WhiskeyName,WhiskeyDescription,WhiskeyScoreSetting,WhiskeyFinish,WhiskeyAroma,WhiskeyTaste,TotalScore,WhiskeyImageUrl,TastedDate,ImageFile")] Whiskey whiskey)
        {

            if (!whiskey.IsTastedDateVaild())
                ModelState.AddModelError(nameof(whiskey.TastedDate), "Missing Tasted Date");

            if (whiskey.ImageFile != null && ModelState.IsValid)
                _uploadManager.CheckImageFileState(whiskey.ImageFile);

            if (ModelState.IsValid)
            {
                _context.Add(whiskey);

                await _context.SaveChangesAsync();

                if (whiskey.ImageFile != null)
                {
                    whiskey.WhiskeyImageUrl = await _uploadManager.AsyncSingleFileUpload(whiskey.ImageFile, whiskey.WhiskeyId.ToString()); // Fun fact, after adding the item to the DB, EF will hydrate the model with ID. Thats why we can use it here.

                    await _context.SaveChangesAsync(); // Not prefered to have another update, but I don't know an easier way to get the generated id of a newly created item without creating it first
                }

                return RedirectToAction(nameof(Index));
            }
            return View(whiskey);
        }

        // GET: WhiskeyAdmin/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var whiskey = await _context.Whiskeys.FindAsync(id);
            if (whiskey == null)
            {
                return NotFound();
            }
            return View(whiskey);
        }

        // POST: WhiskeyAdmin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("WhiskeyId,WhiskeyName,WhiskeyDescription,WhiskeyScoreSetting,UseSurveyResults,DoGenerateTotalScore,WhiskeyFinish,WhiskeyAroma,WhiskeyTaste,TotalScore,WhiskeyImageUrl,TastedDate,ImageFile")] Whiskey whiskey)
        {
            if (id != whiskey.WhiskeyId)
            {
                return NotFound();
            }

            if (whiskey.WhiskeyScoreSetting != WhiskeyScoreSetting.SurveyResults)
            {
                if (!whiskey.IsTastedDateVaild())
                {
                    ModelState.AddModelError(nameof(whiskey.TastedDate), "Missing Tasted Date");
                }
            }
            if (whiskey.ImageFile != null && ModelState.IsValid)
                _uploadManager.CheckImageFileState(whiskey.ImageFile);

            if (ModelState.IsValid)
            {
                if (whiskey.ImageFile != null)
                    whiskey.WhiskeyImageUrl = await _uploadManager.AsyncSingleFileUpload(whiskey.ImageFile, whiskey.WhiskeyId.ToString());

                try
                {
                    _context.Update(whiskey);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WhiskeyExists(whiskey.WhiskeyId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(whiskey);
        }

        // GET: WhiskeyAdmin/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var whiskey = await _context.Whiskeys
                .FirstOrDefaultAsync(m => m.WhiskeyId == id);
            if (whiskey == null)
            {
                return NotFound();
            }

            return View(whiskey);
        }

        // POST: WhiskeyAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var whiskey = await _context.Whiskeys.FindAsync(id);
            if (whiskey != null)
            {
                _context.RemoveRange(_context.TastingResponses.Where(x => x.TastingItem.Whiskey.WhiskeyId == id));
                _context.RemoveRange(_context.TastingItems.Where(x => x.Whiskey.WhiskeyId == id));
                _uploadManager.DeleteUploadedImage(whiskey.WhiskeyImageUrl);
                _context.Whiskeys.Remove(whiskey);
                _context.TastingItems.Where(x => x.Whiskey.WhiskeyId == id);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WhiskeyExists(int id)
        {
            return _context.Whiskeys.Any(e => e.WhiskeyId == id);
        }
    }
}

PWS/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PWS</title>

    @*--- Style Sheets ---*@
    <link rel="stylesheet" href="~/css/BootsWatchTheme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/lightbox.css" /> 
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/PWS.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/bootstrap-icons.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.14.0/themes/base/jquery-ui.css">
    @* <link rel="icon" href="favicon.ico?v=2" type="image/x-icon" /> *@
    <link rel="bookmark icon" href="~/favicon.ico" type="image/x-icon">
</head>
<body class="mb-md-5">
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark" id="nav">
            <div class="container-fluid">
                <a asp-controller="home" asp-action="index">
                    <img src="~/images/logo_title/Unicorntitle.png" alt="PWS Logo"
                         style="height:10VH; margin-bottom:-.5%;margin-top:-.5%; margin-right:.5%; max-height: 15VH;min-height: 70px;" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse ms-3"  id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item me-2">
                            <a class="nav-link text-secondary"  asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item me-2">
                            <a class="nav-link text-secondary" asp-area="" asp-controller="Home" asp-action="AboutUs">About us</a>
                        </li>
                        <li class="nav-item me-2">
                            <a class="nav-link text-secondary" asp-area="" asp-controller="Gallery" asp-action="Index">Photo Gallery</a>
                        </li>
                        <li class="nav-item me-2">
                            <a class="nav-link text-secondary" asp-area="" asp-controller="Blog" asp-action="Index">Blog</a>
                        </li>
                        <li class="nav-item me-2">
                            <a class="nav-link text-secondary" asp-area="" asp-controller="WhiskeyDatabase" asp-action="Index">Whisky</a>
                        </li>

                        <vc:survey-years></vc:survey-years>

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown ms-2">
                                <a class="nav-link text-warning dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Admin</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="" asp-controller="SurveysAdmin" asp-action="Index">Survey</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="" asp-controller="WhiskeyAdmin" asp-action="Index">Whisky</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="" asp-controller="BlogAdmin" asp-action="Index">Blog</a>

                                </div>
                            </li>
                        }       
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container flex-grow-1 mb-5">
        <main role="main" class="pb-3">
            @RenderBody()
        </main> 
    </div>
 

    <br>
    <br>
    <br>





     
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.14.0/jquery-ui.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        //sets a delay so correct size can be calculated avter a maximize event
        function sleep(ms) {
            return new Promise(resolve => setTimeout(resolve, ms));
        }
        //sets the --vw css property to 1% of visible page width
        async function setVw() {
            //first set it to 1vw to get an aproximation of the correct size after resize event so vertical scrollbars show if needed
            document.documentElement.style.setProperty('--vw', `1vw`);
            //wait for resize to happen
            await sleep(500)
            //set --vw back to 1% of the available view
            var vw = document.documentElement.clientWidth / 100;
            document.documentElement.style.setProperty('--vw', `${vw}px`);
        }

        setVw();
        window.addEventListener('resize', setVw);
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
<footer class="border-top footer text-muted mt-5">
    <div class="container">
        <div class="fs-5">
            &copy; 2024 - PWS - <a class="text-decoration-none text-info" asp-controller="Home" asp-action="Contact">Contact Us</a>
            <partial name="_LoginPartial" />
        </div>
    </div>
</footer>
</html>


 